# coding: utf-8

"""
    Giphy API

    Giphy API

    The version of the OpenAPI document: 1.0
    Contact: support@giphy.com
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import giphy_python_sdk
from giphy_python_sdk.paths.stickers_search import get
from giphy_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestStickersSearch(ApiTestMixin, unittest.TestCase):
    """
    StickersSearch unit test stubs
        Search Stickers
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
