# coding: utf-8

"""
    Giphy API

    Giphy API

    The version of the OpenAPI document: 1.0
    Contact: support@giphy.com
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from giphy_python_sdk import Giphy

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        giphy = Giphy(
        
                        api_key = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(giphy)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
