# coding: utf-8

"""
    Giphy API

    Giphy API

    The version of the OpenAPI document: 1.0
    Contact: support@giphy.com
    Generated by: https://konfigthis.com
"""

from giphy_python_sdk.paths.stickers_search.get import FindAnimatedStickers
from giphy_python_sdk.paths.stickers_random.get import GetRandom
from giphy_python_sdk.paths.stickers_trending.get import GetTrending
from giphy_python_sdk.paths.stickers_translate.get import TranslatePhraseToSticker
from giphy_python_sdk.apis.tags.stickers_api_raw import StickersApiRaw


class StickersApi(
    FindAnimatedStickers,
    GetRandom,
    GetTrending,
    TranslatePhraseToSticker,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: StickersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = StickersApiRaw(api_client)
