# coding: utf-8

"""
    Giphy API

    Giphy API

    The version of the OpenAPI document: 1.0
    Contact: support@giphy.com
    Generated by: https://konfigthis.com
"""

from giphy_python_sdk.paths.stickers_search.get import FindAnimatedStickersRaw
from giphy_python_sdk.paths.stickers_random.get import GetRandomRaw
from giphy_python_sdk.paths.stickers_trending.get import GetTrendingRaw
from giphy_python_sdk.paths.stickers_translate.get import TranslatePhraseToStickerRaw


class StickersApiRaw(
    FindAnimatedStickersRaw,
    GetRandomRaw,
    GetTrendingRaw,
    TranslatePhraseToStickerRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
