# coding: utf-8

"""
    Giphy API

    Giphy API

    The version of the OpenAPI document: 1.0
    Contact: support@giphy.com
    Generated by: https://konfigthis.com
"""

import unittest

import giphy_python_sdk
from giphy_python_sdk.model.gif_featured_tags import GifFeaturedTags
from giphy_python_sdk import configuration


class TestGifFeaturedTags(unittest.TestCase):
    """GifFeaturedTags unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
