# coding: utf-8

"""
    Giphy API

    Giphy API

    The version of the OpenAPI document: 1.0
    Contact: support@giphy.com
    Generated by: https://konfigthis.com
"""

import unittest

import giphy_python_sdk
from giphy_python_sdk.model.stickers_get_random_response import StickersGetRandomResponse
from giphy_python_sdk import configuration


class TestStickersGetRandomResponse(unittest.TestCase):
    """StickersGetRandomResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
