# coding: utf-8

"""
    Giphy API

    Giphy API

    The version of the OpenAPI document: 1.0
    Contact: support@giphy.com
    Generated by: https://konfigthis.com
"""

import unittest

import giphy_python_sdk
from giphy_python_sdk.model.gifs_get_trending_gifs_response import GifsGetTrendingGifsResponse
from giphy_python_sdk import configuration


class TestGifsGetTrendingGifsResponse(unittest.TestCase):
    """GifsGetTrendingGifsResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
