# coding: utf-8

"""
    Giphy API

    Giphy API

    The version of the OpenAPI document: 1.0
    Contact: support@giphy.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from giphy_python_sdk.type.gif_featured_tags import GifFeaturedTags
from giphy_python_sdk.type.gif_images import GifImages
from giphy_python_sdk.type.gif_tags import GifTags
from giphy_python_sdk.type.user import User

class RequiredGif(TypedDict):
    pass

class OptionalGif(TypedDict, total=False):
    tags: GifTags

    # The unique bit.ly URL for this GIF
    bitly_url: str

    # Currently unused
    content_url: str

    # The date this GIF was added to the GIPHY database.
    create_datetime: datetime

    # A URL used for embedding this GIF
    embded_url: str

    featured_tags: GifFeaturedTags

    # This GIF's unique ID
    id: str

    images: GifImages

    # The creation or upload date from this GIF's source.
    import_datetime: datetime

    # The MPAA-style rating for this content. Examples include Y, G, PG, PG-13 and R
    rating: str

    # The unique slug used in this GIF's URL
    slug: str

    # The page on which this GIF was found
    source: str

    # The URL of the webpage on which this GIF was found.
    source_post_url: str

    # The top level domain of the source URL.
    source_tld: str

    # The date on which this gif was marked trending, if applicable.
    trending_datetime: datetime

    # Type of the gif. By default, this is almost always gif
    type: str

    # The date on which this GIF was last updated.
    update_datetime: datetime

    # The unique URL for this GIF
    url: str

    user: User

    # The username this GIF is attached to, if applicable
    username: str

class Gif(RequiredGif, OptionalGif):
    pass
