# coding: utf-8

"""
    Giphy API

    Giphy API

    The version of the OpenAPI document: 1.0
    Contact: support@giphy.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredImage(TypedDict):
    pass

class OptionalImage(TypedDict, total=False):
    # The number of frames in this GIF.
    frames: str

    # The height of this GIF in pixels.
    height: str

    # The URL for this GIF in .MP4 format.
    mp4: str

    # The size in bytes of the .MP4 file corresponding to this GIF.
    mp4_size: str

    # The size of this GIF in bytes.
    size: str

    # The publicly-accessible direct URL for this GIF.
    url: str

    # The URL for this GIF in .webp format.
    webp: str

    # The size in bytes of the .webp file corresponding to this GIF.
    webp_size: str

    # The width of this GIF in pixels.
    width: str

class Image(RequiredImage, OptionalImage):
    pass
