# coding: utf-8

"""
    Giphy API

    Giphy API

    The version of the OpenAPI document: 1.0
    Contact: support@giphy.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredMeta(TypedDict):
    pass

class OptionalMeta(TypedDict, total=False):
    # HTTP Response Message
    msg: str

    # A unique ID paired with this response from the API.
    response_id: str

    # HTTP Response Code
    status: int

class Meta(RequiredMeta, OptionalMeta):
    pass
