# coding: utf-8

"""
    Giphy API

    Giphy API

    The version of the OpenAPI document: 1.0
    Contact: support@giphy.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Image(BaseModel):
    # The number of frames in this GIF.
    frames: typing.Optional[str] = Field(None, alias='frames')

    # The height of this GIF in pixels.
    height: typing.Optional[str] = Field(None, alias='height')

    # The URL for this GIF in .MP4 format.
    mp4: typing.Optional[str] = Field(None, alias='mp4')

    # The size in bytes of the .MP4 file corresponding to this GIF.
    mp4_size: typing.Optional[str] = Field(None, alias='mp4_size')

    # The size of this GIF in bytes.
    size: typing.Optional[str] = Field(None, alias='size')

    # The publicly-accessible direct URL for this GIF.
    url: typing.Optional[str] = Field(None, alias='url')

    # The URL for this GIF in .webp format.
    webp: typing.Optional[str] = Field(None, alias='webp')

    # The size in bytes of the .webp file corresponding to this GIF.
    webp_size: typing.Optional[str] = Field(None, alias='webp_size')

    # The width of this GIF in pixels.
    width: typing.Optional[str] = Field(None, alias='width')
    class Config:
        arbitrary_types_allowed = True
