# coding: utf-8

"""
    Giphy API

    Giphy API

    The version of the OpenAPI document: 1.0
    Contact: support@giphy.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Meta(BaseModel):
    # HTTP Response Message
    msg: typing.Optional[str] = Field(None, alias='msg')

    # A unique ID paired with this response from the API.
    response_id: typing.Optional[str] = Field(None, alias='response_id')

    # HTTP Response Code
    status: typing.Optional[int] = Field(None, alias='status')
    class Config:
        arbitrary_types_allowed = True
