# coding: utf-8

"""
    Giphy API

    Giphy API

    The version of the OpenAPI document: 1.0
    Contact: support@giphy.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Pagination(BaseModel):
    # Total number of items returned.
    count: typing.Optional[int] = Field(None, alias='count')

    # Position in pagination.
    offset: typing.Optional[int] = Field(None, alias='offset')

    # Total number of items available.
    total_count: typing.Optional[int] = Field(None, alias='total_count')
    class Config:
        arbitrary_types_allowed = True
