# coding: utf-8

"""
    Giphy API

    Giphy API

    The version of the OpenAPI document: 1.0
    Contact: support@giphy.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class User(BaseModel):
    # The URL for this user's avatar image.
    avatar_url: typing.Optional[str] = Field(None, alias='avatar_url')

    # The URL for the banner image that appears atop this user's profile page.
    banner_url: typing.Optional[str] = Field(None, alias='banner_url')

    # The display name associated with this user (contains formatting the base username might not).
    display_name: typing.Optional[str] = Field(None, alias='display_name')

    # The URL for this user's profile.
    profile_url: typing.Optional[str] = Field(None, alias='profile_url')

    # The Twitter username associated with this user, if applicable.
    twitter: typing.Optional[str] = Field(None, alias='twitter')

    # The username associated with this user.
    username: typing.Optional[str] = Field(None, alias='username')
    class Config:
        arbitrary_types_allowed = True
